modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/eutro/FramedCompactDrawers/issues"
[[mods]]
modId="framedcompactdrawers"
version="${file.jarVersion}"
displayName="Framed Compacting Drawers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers"
logoFile="logo.png"
authors="Eutros"
description='''
Adds a framed version of the Compacting Drawers from the Storage Drawers mod.
'''
[[dependencies.framedcompactdrawers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.framedcompactdrawers]]
    modId="storagedrawers"
    mandatory=true
    versionRange="[10.2,)"
    ordering="NONE"
    side="BOTH"
